version: "3.4"
services:
  api:
    container_name: todo_api
    build:
      context: api
      target: api_dev
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  client:
    container_name: todo_client
    build:
      context: ./client
      target: client_dev
    ports:
      - '3000:3000'
    depends_on:
      - server
  mongo:
    container_name: todo_db
    image: 'mongo'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
