#!/bin/bash

COMMIT_REGEX="^TL-[0-9]+:\s.{15,}\."
error_msg="Invalid commit message \"$(head -n 1 $1)\". Pattern: \"$COMMIT_REGEX\".\n"

if ! grep -iqE "$COMMIT_REGEX" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
